// Global test setup: DOM matchers and environment resets.
import "@testing-library/jest-dom/vitest";
import { afterEach, describe, expect, it } from "vitest";
import { cleanup } from "@testing-library/react";

// Ensure the DOM is clean between tests to avoid state leaking across cases.
afterEach(() => {
  cleanup();
});

// jsdom implements neither object-URL function, and the export path needs both
// to turn generated bytes into a download. A stub is enough: tests assert on the
// bytes handed over, not on what the browser does with them.
if (typeof URL.createObjectURL !== "function") {
  URL.createObjectURL = () => "blob:test";
}
if (typeof URL.revokeObjectURL !== "function") {
  URL.revokeObjectURL = () => {
    /* no-op */
  };
}

// Convenience aliases so test files can stay terse.
export { describe, expect, it };
